# Generated by Django 3.2.7 on 2021-09-25 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0002_auto_20210925_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('adress', models.TextField(verbose_name='Адресс')),
                ('location', models.TextField(verbose_name='Гео-локация')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
    ]
