# Generated by Django 3.2.7 on 2021-09-26 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0004_alter_profile_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('measurement', models.TextField(verbose_name='Ед. измер.')),
                ('amount', models.TextField(verbose_name='Количество')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.category', verbose_name='Категория')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.company', verbose_name='Компания')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.storage', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
