# Generated by Django 3.2.7 on 2021-10-07 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0006_alter_product_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('status', models.TextField(verbose_name='Статус')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.company', verbose_name='Компания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.product', verbose_name='Товар')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.storage', verbose_name='Склад')),
            ],
            options={
                'verbose_name': ('Заявка',),
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
