# Generated by Django 3.2.7 on 2021-10-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0007_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_id',
            field=models.PositiveIntegerField(default=123, unique=True, verbose_name='Номер заявки '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='user_id',
            field=models.PositiveIntegerField(default=5335, verbose_name='ID пользователя'),
            preserve_default=False,
        ),
    ]
