# Generated by Django 3.2.7 on 2021-10-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0008_auto_20211008_1739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='Applications',
        ),
    ]
