# Generated by Django 3.2.7 on 2021-10-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0009_rename_application_applications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='app_id',
        ),
    ]
