# Generated by Django 3.2.7 on 2021-10-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0010_remove_applications_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='amount_before',
            field=models.BigIntegerField(default=1234, verbose_name='Кол-во без изменения'),
            preserve_default=False,
        ),
    ]
