# Generated by Django 3.2.7 on 2021-10-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0012_remove_applications_amount_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='counter',
            field=models.IntegerField(default=1, verbose_name='Счётчик'),
            preserve_default=False,
        ),
    ]
