# Generated by Django 3.2.7 on 2021-10-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0016_alter_product_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='location',
        ),
        migrations.AddField(
            model_name='storage',
            name='latitude',
            field=models.FloatField(default=38.8951, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='longitude',
            field=models.FloatField(default=-77.0364, verbose_name='Долгота'),
            preserve_default=False,
        ),
    ]
