# Generated by Django 3.2.7 on 2021-10-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0017_auto_20211013_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='change_amount',
            field=models.TextField(default=0, verbose_name='Количество для изменения'),
            preserve_default=False,
        ),
    ]
