# Generated by Django 3.2.7 on 2021-10-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0019_alter_profile_change_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='change_prod',
            field=models.TextField(default=0, verbose_name='Продукт для изменения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='change_amount',
            field=models.FloatField(default=0, verbose_name='Количество для изменения'),
        ),
    ]
