# Generated by Django 3.2.7 on 2021-10-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0020_auto_20211015_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='product',
            field=models.TextField(verbose_name='Товар'),
        ),
    ]
