# Generated by Django 3.2.7 on 2021-10-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0021_alter_applications_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='change_measurement',
            field=models.TextField(default=0, verbose_name='Ед. изм.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='selected_company',
            field=models.TextField(default=0, verbose_name='Выбранная компания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='selected_storage',
            field=models.TextField(default=0, verbose_name='Выбранный склад'),
            preserve_default=False,
        ),
    ]
