# Generated by Django 3.2.7 on 2021-10-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0022_auto_20211027_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='change_measurement',
            field=models.TextField(default=0, verbose_name='Ед. изм.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='selected_company',
            field=models.TextField(default=0, verbose_name='Выбранная компания'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='selected_storage',
            field=models.TextField(default=0, verbose_name='Выбранный склад'),
        ),
    ]
