# Generated by Django 3.2.7 on 2021-10-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0023_auto_20211027_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='company',
            field=models.TextField(verbose_name='Компания'),
        ),
    ]
