# Generated by Django 3.2.7 on 2021-10-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0024_alter_applications_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='storage',
            field=models.TextField(verbose_name='Склад'),
        ),
    ]
