# Generated by Django 3.2.7 on 2021-10-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0027_remove_profile_selected_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='company',
            field=models.TextField(verbose_name='Компания'),
        ),
    ]
