# Generated by Django 3.2.7 on 2021-10-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0028_alter_applications_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.TextField(verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.TextField(verbose_name='Склад'),
        ),
    ]
