# Generated by Django 3.2.7 on 2021-10-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0029_auto_20211028_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_page',
            field=models.TextField(default='start', verbose_name='Действующая страница'),
        ),
        migrations.AddField(
            model_name='profile',
            name='previous_page',
            field=models.TextField(default='start', verbose_name='Предыдущая страница'),
        ),
    ]
