# Generated by Django 3.2.7 on 2021-11-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0032_auto_20211101_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='reason',
            field=models.TextField(default=0, verbose_name='Reason of denying'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.TextField(verbose_name='Status'),
        ),
    ]
