# Generated by Django 3.2.7 on 2021-11-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0033_auto_20211112_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.TextField(default=0, verbose_name='state of addition'),
            preserve_default=False,
        ),
    ]
