# Generated by Django 3.2.7 on 2021-11-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0034_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='create_name',
            field=models.TextField(default=0, verbose_name='Name of new product'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.TextField(verbose_name='State of addition'),
        ),
    ]
