# Generated by Django 3.2.7 on 2021-11-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0035_auto_20211112_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected_category',
            field=models.TextField(default=0, verbose_name='Selected category'),
        ),
    ]
