# Generated by Django 3.2.7 on 2021-11-12 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0036_profile_selected_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='selected_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.category'),
        ),
    ]
