# Generated by Django 3.2.7 on 2021-11-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0038_application_callback'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_callback',
            name='stat',
            field=models.TextField(default=0, verbose_name='Application status'),
            preserve_default=False,
        ),
    ]
